package com.skillforge;

import java.security.MessageDigest;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.Map;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@SpringBootApplication
@RestController
@RequestMapping("/api/auth")
@CrossOrigin(origins = {"http://localhost:5173", "http://127.0.0.1:5173"})
public class SkillForgeApplication {
    private final JdbcTemplate db;
    public SkillForgeApplication(JdbcTemplate db) { this.db = db; }
    public static void main(String[] args) { SpringApplication.run(SkillForgeApplication.class, args); }

    @Bean
    CommandLineRunner initializeDatabase() {
        return args -> db.execute("CREATE TABLE IF NOT EXISTS users (" +
            "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "name VARCHAR(100) NOT NULL, email VARCHAR(150) UNIQUE NOT NULL, " +
            "password_hash VARCHAR(500) NOT NULL)");
    }

    public record AuthRequest(String name, String email, String password) {}

    private String hashPassword(String password) throws Exception {
        byte[] salt = new byte[16];
        new SecureRandom().nextBytes(salt);
        PBEKeySpec spec = new PBEKeySpec(password.toCharArray(), salt, 210000, 256);
        byte[] hash = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();
        spec.clearPassword();
        return Base64.getEncoder().encodeToString(salt) + ":" + Base64.getEncoder().encodeToString(hash);
    }

    private boolean verifyPassword(String password, String stored) throws Exception {
        String[] parts = stored.split(":");
        byte[] salt = Base64.getDecoder().decode(parts[0]);
        byte[] expected = Base64.getDecoder().decode(parts[1]);
        PBEKeySpec spec = new PBEKeySpec(password.toCharArray(), salt, 210000, 256);
        byte[] actual = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();
        spec.clearPassword();
        return MessageDigest.isEqual(expected, actual);
    }

    @PostMapping("/register")
    public ResponseEntity<?> register(@RequestBody AuthRequest r) {
        try {
            if (r.name() == null || r.name().isBlank() || r.email() == null ||
                r.password() == null || r.password().length() < 8) {
                return ResponseEntity.badRequest().body(Map.of("message", "Enter your name, email, and a password of at least 8 characters."));
            }
            String email = r.email().trim().toLowerCase();
            if (!email.matches("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$")) {
                return ResponseEntity.badRequest().body(Map.of("message", "Enter a valid email address."));
            }
            Integer count = db.queryForObject("SELECT COUNT(*) FROM users WHERE email = ?", Integer.class, email);
            if (count != null && count > 0) {
                return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("message", "This email is already registered."));
            }
            db.update("INSERT INTO users (name,email,password_hash) VALUES (?,?,?)", r.name().trim(), email, hashPassword(r.password()));
            return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message", "Registration successful. Please log in."));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("message", "Registration failed. Please try again."));
        }
    }

    @PostMapping("/login")
    public ResponseEntity<?> login(@RequestBody AuthRequest r) {
        try {
            if (r.email() == null || r.password() == null) {
                return ResponseEntity.badRequest().body(Map.of("message", "Email and password are required."));
            }
            var users = db.query("SELECT id,name,email,password_hash FROM users WHERE email = ?",
                (rs, n) -> Map.<String,Object>of("id", rs.getLong("id"), "name", rs.getString("name"),
                    "email", rs.getString("email"), "password_hash", rs.getString("password_hash")),
                r.email().trim().toLowerCase());
            if (users.isEmpty() || !verifyPassword(r.password(), (String) users.get(0).get("password_hash"))) {
                return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("message", "Invalid email or password."));
            }
            var u = users.get(0);
            return ResponseEntity.ok(Map.of("message", "Login successful.", "id", u.get("id"),
                "name", u.get("name"), "email", u.get("email")));
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body(Map.of("message", "Login failed. Please try again."));
        }
    }
}
